### ISSUE TITLE
Error "bezier slider was too big"

### ISSUE THREAD

**Issue by wubbledubble** [thebetioplane/osuReplayEditorV3#18]
When trying to load a replay for this map (https://osu.ppy.sh/beatmapsets/933630#osu/1949106) I get this error. I can load other replay files perfectly fine so I'm not sure what the problem is. Maybe the length of the map? I can upload a recording of the issue or any file that would help you.

![Screenshot_45](https://user-images.githubusercontent.com/80721261/111224424-af282180-859b-11eb-9407-80d43970af86.png)

**Comment by thebetioplane** [comment]
It's the length of a slider. When the number of control points is more than 100 the algorithm is slow, so I put a hard limit. This slider in the map has 748 control points so that is what you are seeing.
![screenshot](https://user-images.githubusercontent.com/13561330/111342154-14e6dd00-8672-11eb-9137-907eafa4fa94.jpg)
I will have to switch the algorithm.

**Comment by thebetioplane** [comment]
I switched Bezier slider algorithms. I confirmed that it fixes this map, but I think the performance of all Bezier sliders is increased now.
