### ISSUE TITLE
Compatible read .osr from Dropout

### ISSUE THREAD

**Issue by KecHik445** [thebetioplane/osuReplayEditorV3#24]
It is possible to read .osr that are export from Dropout (another replay editor) on this V3? Opening the .osr/replay from that program crash V3 but fine on osu! client.

The replay : https://drive.google.com/file/d/1Iz9kxqvTKWkwlxsvVQ_e9OUWgDWBcyMj/view?usp=sharing

**Comment by thebetioplane** [comment]
Hi,

Just fixed this because it quite small and as you mentioned osu! can read this replay fine.

However, if you are interested in the reason why it couldn't be loaded before it was because the replay string (the LZMA compressed data) did not end with a comma.

These are the last two frames of your replay: `25|374.9844|276.5635|0,-12345|0|0|0`

And these are the last two frames of one produced by osu!: `14|-256|466.1333|0,-12345|0|0|19467063,`

It is osu!'s behavior to always append this comma to the end of the replay. I'm not familiar with other replay editors but if you know the developer you can tell them that their output deviates from osu (if they care).

**Comment by KecHik445** [comment]
Thank you for the fix!
