### ISSUE TITLE
Editor becomes really laggy when opened the replay

### ISSUE THREAD

**Issue by Hazuki-san** [thebetioplane/osuReplayEditorV3#27]
In the old update, it doesn't freeze

**Comment by Hazuki-san** [comment]
https://user-images.githubusercontent.com/27200811/131440290-7b60f3b4-b652-46f0-9a03-34e2cbee408c.mp4

**Comment by thebetioplane** [comment]
Does this happen with every replay or just this one?

**Comment by Hazuki-san** [comment]
> Does this happen with every replay or just this one?
> And just to confirm since it's a bit blurry in the video for me... task manager was not showing high CPU, RAM, or disk usage for osuReplayEditor.exe?

Yes, it happens with all replays. And osuReplayEditor.exe doesn't use all the RAM, CPU or Disk Usage.

**Comment by thebetioplane** [comment]
Very confusing... doesn't happen on my machine. Looks indicative of high CPU but task manager says otherwise, therefore even profiling doesn't help me.

The best I can do if it's not too much trouble is have you try these four builds (drag the exe and dll into your existing folder), and report which ones you experience the issue on?
[old_ver.zip](https://github.com/thebetioplane/osuReplayEditorV3/files/7085281/old_ver.zip)

**Comment by Hazuki-san** [comment]
Odd, the problem has now been fixed by it's own... What a weird issue...
