### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by AwesomeGamer89** [thebetioplane/osuReplayEditorV3#44]
I was just wondering if you could put a changelog anywhere for us to see.

**Comment by thebetioplane** [comment]
Yes, since I've made the source code to this available, the commit messages from that repo can serve as a changelog going forward. As far as historical information, sorry, there is no such record. I was not even keeping track myself.

The link for this changelog is: https://github.com/thebetioplane/osuReplayEditorV3_SRC/commits/master

And clicking these 3 dots shows the longer message if there is one:

![image](https://user-images.githubusercontent.com/13561330/154848830-82bf9467-0c02-4b95-a73c-8ab085827715.png)

**Comment by thebetioplane** [comment]
I would also like to add that it's probably confusing that there are two repositories for the same project now, but it's the best way I could keep compatibility with how the updater works for now
