### ISSUE TITLE
Set replay datetime to current date.

### ISSUE THREAD

**Issue by xxCherry** [thebetioplane/osuReplayEditorV3#6]
If you will set datetime of replay to current date, osu! will import edited replay instead of just do nothing.

**Comment by thebetioplane** [comment]
Could you elaborate what you mean by "importing a new replay". Changing the time and then opening the replay shows the new time for me.

Is what you are talking about related to the fact that the replay hash in the official client is dependent **only** on the max combo, player name, beatmap, total score, and rank? Where mine is dependent on everything -- including timestamp in this case? I was curious what the consequence of that would be, I did it because I thought it would fix the issues of people having to clear local scores in order to see updated replays.

**Comment by xxCherry** [comment]
I mean when user just edit the frames and not metadata, i think it would be useful to update his replay timestamp to make osu! push edited replay as new replay.

**Comment by thebetioplane** [comment]
Are you talking about the replays in the replay cache dir, like `osu!\Data\r\` ?

**Comment by xxCherry** [comment]
yep, i meant local scores in general

**Comment by thebetioplane** [comment]
Ok I'll look into how to best implement, whether it's with a setting or whatnot. I don't want to remove the ability to edit timestamps and always force it to save with an updated date time.

**Comment by thebetioplane** [comment]
I've added a checkbox on the main window that enables or disables updating timestamps on export. This setting is persistent across sessions.

**Comment by xxCherry** [comment]
Thanks.
