### ISSUE TITLE
Can't open osuReplayEditorV3.

### ISSUE THREAD

**Issue by khthch** [thebetioplane/osuReplayEditorV3#60]
I'm check in crash.log
---------------------------
UTC: 2023-03-31 10:25:26
System.DllNotFoundException: Unable to load DLL 'ReplayEditor.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at osuReplayEditor.API.Init(IntPtr hWnd, String osuDBPath, String songFolderPath)
   at osuReplayEditor.Canvas.Begin()
   at osuReplayEditor.MainForm..ctor()
   at osuReplayEditor.Program.Main2()
   at osuReplayEditor.Program.Main(String[] args)
---------------------------
My computer using Windows 7(64bit)
Thank a lot.

**Comment by thebetioplane** [comment]
I think the last time this happened to someone the culprit was missing Microsoft Visual C++ Redistributable 2015-2019.

Could you try installing it? https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

Download the x64 version: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by khthch** [comment]
> I think the last time this happened to someone the culprit was missing Microsoft Visual C++ Redistributable 2015-2019.
> 
> Could you try installing it? https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
> 
> Download the x64 version: https://aka.ms/vs/17/release/vc_redist.x64.exe

My computer missing that files.And it's worked.
Thank you,friend!
